spring.application.name=payflow

# H2 in-memory DB — resets on every restart (great for development)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:payflowdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Print SQL queries in terminal — very helpful for learning
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate creates/updates tables automatically from @Entity classes
spring.jpa.hibernate.ddl-auto=update
